import React from 'react';

export default function LegalPage() {
  return (
    <div className="bg-warm-ivory dark:bg-[#111] transition-colors min-h-[100dvh] text-mistral-black dark:text-warm-ivory py-20 px-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-[clamp(3rem,6vw,82px)] font-normal leading-[0.95] tracking-display uppercase mb-12">
          LEGAL & PRIVACY
        </h1>
        
        <div className="prose prose-mistral dark:prose-invert prose-lg max-w-none bg-white dark:bg-mistral-black transition-colors p-8 md:p-12 border border-mistral-black/10 dark:border-warm-ivory/10 shadow-mistral">
          <p className="text-[14px] font-normal uppercase tracking-widest text-mistral-black/50 dark:text-warm-ivory/50 mb-8 border-b border-mistral-black/10 dark:border-warm-ivory/10 pb-4">Last Updated: April 2026</p>

          <h2 className="text-[32px] font-normal leading-[1.15] mt-10 mb-4 uppercase">1. Terms of Service</h2>
          <p>
            By accessing or using the Searchily platform, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, then you may not access the service. We reserve the right to modify or replace these Terms at any time.
          </p>
          
          <h2 className="text-[32px] font-normal leading-[1.15] mt-10 mb-4 uppercase">2. Privacy Policy</h2>
          <p>
            Your privacy is crucial to us. Searchily collects minimal necessary data to provide our AI-driven discovery service.
          </p>
          <ul>
            <li><strong>Data we collect:</strong> Search queries, conversational history, and interaction analytics to improve ranking quality.</li>
            <li><strong>Data we do NOT collect:</strong> We do not sell your personal data or queries to third-party advertising networks.</li>
          </ul>

          <h2 className="text-[32px] font-normal leading-[1.15] mt-10 mb-4 uppercase">3. AI Generated Content</h2>
          <p>
            Our search results and reasoning are generated by artificial intelligence. While we strive for accuracy, Searchily does not guarantee that the AI representations of products exactly match third-party retailers at all times. Prices and availability are subject to change by the original vendors.
          </p>

          <h2 className="text-[32px] font-normal leading-[1.15] mt-10 mb-4 uppercase">4. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at <strong>legal@searchily.ai</strong>.
          </p>
        </div>
      </div>
    </div>
  );
}
